services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    volumes:
      - /srv/komodo/data/beszel:/beszel_data
      - /srv/komodo/data/beszel/socket:/beszel_socket
    ports:
      - 8090:8090
    labels:
      - "tsbridge.enabled=true"
      - "tsbridge.service.name=beszel"
      - "tsbridge.service.port=8090"   
    networks:
      - tailnet

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/komodo/data/beszel/socket:/beszel_socket
      - /mnt/local-data/beszel:/extra-filesystems/local-data:ro
      - /mnt/media/beszel:/extra-filesystems/media:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: $KEY

networks:
  tailnet:
    external: true