services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    volumes:
      - /srv/komodo/data/beszel:/beszel_data
      - /srv/komodo/data/beszel/socket:/beszel_socket
    ports:
      - 8090:8090
    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=beszel"
    networks:
      - tailnet

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/komodo/data/beszel/socket:/beszel_socket
    environment:
      LISTEN: 45876
      KEY: $KEY

networks:
  tailnet:
    external: true