[[server]]
name = "server-gjwp7"
[server.config]
address = "http://periphery:8120"
enabled = true

##

[[stack]]
name = "tailscale"
[stack.config]
server = "server-gjwp7"
poll_for_updates = true
git_account = "Sadorus"
repo = "Sadorus/homelab"
run_directory = "stacks/tailscale"
file_paths = ["docker-compose.yaml"]
environment = """
TAILSCALE_AUTH_KEY = [[TAILSCALE_AUTH_KEY]]
"""

##

[[stack]]
name = "tsdproxy"
[stack.config]
server = "server-gjwp7"
poll_for_updates = true
git_account = "Sadorus"
repo = "Sadorus/homelab"
run_directory = "stacks/tsdproxy"
file_paths = ["docker-compose.yaml"]

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "server-gjwp7"

##

[[resource_sync]]
name = "github-sync"
[resource_sync.config]
repo = "Sadorus/homelab"
git_account = "Sadorus"
resource_path = ["komodo.toml"]
managed = true