[[server]]
name = "server-gjwp7"
[server.config]
address = "http://periphery:8120"
enabled = true

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "server-gjwp7"

##

[[resource_sync]]
name = "github-sync"
[resource_sync.config]
repo = "Sadorus/homelab"
git_account = "Sadorus"
resource_path = ["komodo.toml"]
managed = true