[[server]]
name = "nas"
[server.config]
address = "http://periphery:8120"
enabled = true

##

[[stack]]
name = "beszel"
[stack.config]
server = "nas"
poll_for_updates = true
git_account = "Sadorus"
repo = "Sadorus/homelab"
run_directory = "stacks/beszel"
file_paths = ["docker-compose.yaml"]
environment = """
PUID = [[PUID]]
KEY = [[KEY]]
"""

##

[[stack]]
name = "bill-tracker"
[stack.config]
server = "nas"
poll_for_updates = true
git_account = "Sadorus"
repo = "Sadorus/homelab"
run_directory = "stacks/bill-tracker"
file_paths = ["docker-compose.yaml"]

##

[[stack]]
name = "glance"
[stack.config]
server = "nas"
poll_for_updates = true
git_account = "Sadorus"
repo = "Sadorus/homelab"
run_directory = "stacks/glance"
file_paths = ["docker-compose.yaml"]

##

[[stack]]
name = "immich"
[stack.config]
server = "nas"
auto_update = true
git_account = "Sadorus"
repo = "Sadorus/homelab"
run_directory = "stacks/immich"
file_paths = ["docker-compose.yaml"]
environment = """
UPLOAD_LOCATION = [[UPLOAD_LOCATION]]

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION = [[DB_DATA_LOCATION]]

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION = [[IMMICH_VERSION]]

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD = [[DB_PASSWORD]]

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME = [[DB_USERNAME]]
DB_DATABASE_NAME = [[DB_DATABASE_NAME]]
"""

##

[[stack]]
name = "qbit_vpn"
[stack.config]
server = "nas"
poll_for_updates = true
git_account = "Sadorus"
repo = "Sadorus/homelab"
run_directory = "stacks/qbit_vpn"
file_paths = ["docker-compose.yaml"]
environment = """
VPN_SERVICE_PROVIDER = [[VPN_SERVICE_PROVIDER]]
VPN_TYPE = [[VPN_TYPE]]
OPENVPN_USER = [[OPENVPN_USER]]
OPENVPN_PASSWORD = [[OPENVPN_PASSWORD]]
SERVER_COUNTRIES = [[SERVER_COUNTRIES]]
TZ = [[TZ]]
PGID = [[PGID]]
PUID = [[PUID]]
WEBUI_PORT = [[WEBUI_PORT]]
"""

##

[[stack]]
name = "tailscale"
tags = ["Proxy"]
[stack.config]
server = "nas"
poll_for_updates = true
git_account = "Sadorus"
repo = "Sadorus/homelab"
run_directory = "stacks/tailscale"
file_paths = ["docker-compose.yaml"]
environment = """
TAILSCALE_AUTH_KEY = [[TAILSCALE_AUTH_KEY]]
"""

##

[[stack]]
name = "tsdproxy"
tags = ["Proxy"]
[stack.config]
server = "nas"
poll_for_updates = true
git_account = "Sadorus"
repo = "Sadorus/homelab"
run_directory = "stacks/tsdproxy"
file_paths = ["docker-compose.yaml"]

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "nas"

##

[[resource_sync]]
name = "github-sync"
[resource_sync.config]
repo = "Sadorus/homelab"
git_account = "Sadorus"
resource_path = ["komodo.toml"]
managed = true
delete = true