services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - /srv/komodo/data/glance/config:/app/config
      - /srv/komodo/data/glance/assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8082:8080
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=glance
      - tsdproxy.container_port=8080  # Explicitly specify the internal port
      - tsdproxy.host_port=8082  
      - tsdproxy.ssl=true
    networks:
      - tailnet

networks:
  tailnet:
    external: true