services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - /srv/komodo/data/glance/config:/app/config
      - /srv/komodo/data/glance/assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8082:8000
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=glance
      - tsdproxy.port=8080
    networks:
      - tailnet

networks:
  tailnet:
    external: true